// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Infra.Database;

#nullable disable

namespace TodoList.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220701172941_TabelaTaskDetails")]
    partial class TabelaTaskDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoList.Core.Entities.TaskDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataHora")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.Property<int>("Executado")
                        .HasColumnType("INT");

                    b.Property<int>("IdTaskList")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTaskList");

                    b.ToTable("taskdetails", (string)null);
                });

            modelBuilder.Entity("TodoList.Core.Entities.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("tasklists", (string)null);
                });

            modelBuilder.Entity("TodoList.Core.Entities.TaskDetail", b =>
                {
                    b.HasOne("TodoList.Core.Entities.TaskList", "TaskList")
                        .WithMany("Details")
                        .HasForeignKey("IdTaskList")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("TodoList.Core.Entities.TaskList", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
